/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#71d7cd",
        "on-surface": "#2d3335",
        "primary-fixed": "#79bff8",
        "error-container": "#fa746f",
        "error": "#a83836",
        "primary-dim": "#005885",
        "error-dim": "#67040d",
        "outline-variant": "#adb3b5",
        "surface-container": "#ebeef0",
        "on-secondary-fixed-variant": "#006666",
        "on-tertiary-fixed-variant": "#005d57",
        "secondary-dim": "#005d5d",
        "on-primary-fixed-variant": "#004367",
        "tertiary-fixed": "#7fe6db",
        "on-secondary-container": "#005c5c",
        "secondary": "#006a6a",
        "inverse-on-surface": "#9b9d9e",
        "surface": "#f8f9fa",
        "secondary-fixed-dim": "#85e4e3",
        "on-surface-variant": "#5a6062",
        "secondary-container": "#93f2f2",
        "on-error-container": "#6e0a12",
        "primary": "#006497",
        "primary-container": "#79bff8",
        "on-primary": "#f6f9ff",
        "on-tertiary-fixed": "#003e39",
        "on-primary-container": "#003a5a",
        "on-primary-fixed": "#002338",
        "surface-bright": "#f8f9fa",
        "on-tertiary": "#e2fffa",
        "tertiary": "#006b64",
        "tertiary-container": "#7fe6db",
        "outline": "#767c7e",
        "on-tertiary-container": "#00534d",
        "primary-fixed-dim": "#6bb2e9",
        "surface-dim": "#d5dbdd",
        "inverse-surface": "#0c0f10",
        "surface-container-low": "#f1f4f5",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#dee3e6",
        "secondary-fixed": "#93f2f2",
        "on-secondary-fixed": "#004747",
        "surface-variant": "#dee3e6",
        "inverse-primary": "#79bff8",
        "on-secondary": "#e0fffe",
        "background": "#f8f9fa",
        "surface-tint": "#006497",
        "surface-container-high": "#e5e9eb",
        "tertiary-dim": "#005e57",
        "on-error": "#fff7f6",
        "on-background": "#2d3335"
      },
      fontFamily: {
        "headline": ["Public Sans"],
        "body": ["Public Sans"],
        "label": ["Public Sans"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
